# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LR <- function(y_, x_) {
    .Call(`_Teste_LR`, y_, x_)
}

myfunction <- function(y) {
    .Call(`_Teste_myfunction`, y)
}

